baseurl: "/course-template"             # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://mbmosman.github.io"  # the base hostname & protocol for your site

title: "My Course"

course_full_title: "My Longer Course Title"
course_number: CCIS XXXX
semester: Fall 2015

gems:
  - jemoji

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"

permalink: :title

# Color scheme based on http://flatuicolors.com/.
# Possible values:
# - silver
# - gold
# - midnight
# - turquoise
# - green
# - blue
# - purple
# - orange
# - red
theme_color: orange

collections:
  semesters:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "semesters"
    values:
      layout: "semester"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
